
drop table TBMEMBER
CASCADE CONSTRAINTS;

CREATE TABLE TB_MEMBER(
    NAME VARCHAR2(16) NOT NULL, 
    TEL VARCHAR2(13) NOT NULL, 
    DEPT VARCHAR2(50) NOT NULL, 
    AGE VARCHAR2(50) NOT NULL
);

SELECT * FROM TB_MEMBER

